# Makefile to generate final rom bits
#
# Copyright (C) 2013, Broadcom Corporation
# All Rights Reserved.
#
# This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
# the contents of this file may not be disclosed to third parties, copied
# or duplicated in any form, in whole or in part, without the prior
# written permission of Broadcom Corporation.
#
# $Id: Makefile$
# Makefile to generate final rom bits

CHIP = 43602a1

ROMTBL_VARIANT = pcie
ROMTBL_TGT = $(CHIP)/$(ROMTBL_VARIANT)

# CLM info
CLM_TYPE	:= 43602a1
TCAM_ONLY	:= 1

include ../Makefile.cmn
