/*
 *-----------------------------------------------------------------------------
 * Copyright (C) 2014, Broadcom Corporation
 * All Rights Reserved.
 * 
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom Corporation.
 *-----------------------------------------------------------------------------
 *
 * DO NOT EDIT THIS FILE, IT WAS MACHINE GENERATED
 * by shenoys on Mon Apr 21 17:49:26 2014 using:
 *
 *  $ txgaintables_tcl2c.py 47xxtcl wlc_phytbl_ac_gains.h wlc_phytbl_ac_gains.c
 *
 * $Id$
 */
/* FILE-CSTYLED */

#ifndef WLC_PHYTBL_AC_GAINS_H_
#define WLC_PHYTBL_AC_GAINS_H_

#include <typedefs.h>

#define TXGAIN_TABLES_LEN 384
extern const uint16 txgain_tiny_phyrev4_5g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev4_5g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_2g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_2g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_5g_1_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_5g_epa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_5g_ipa[TXGAIN_TABLES_LEN];
extern const uint16 txgain_tiny_phyrev7_ipa_2g_for_epa[TXGAIN_TABLES_LEN];

#endif /* WLC_PHYTBL_AC_GAINS_H_ */
