# <:copyright-BRCM:2019:proprietary:standard
# 
#    Copyright (c) 2019 Broadcom 
#    All Rights Reserved
# 
#  This program is the proprietary software of Broadcom and/or its
#  licensors, and may only be used, duplicated, modified or distributed pursuant
#  to the terms and conditions of a separate, written license agreement executed
#  between you and Broadcom (an "Authorized License").  Except as set forth in
#  an Authorized License, Broadcom grants no license (express or implied), right
#  to use, or waiver of any kind with respect to the Software, and Broadcom
#  expressly reserves all rights in and to the Software and all intellectual
#  property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU HAVE
#  NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY
#  BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
# 
#  Except as expressly set forth in the Authorized License,
# 
#  1. This program, including its structure, sequence and organization,
#     constitutes the valuable trade secrets of Broadcom, and you shall use
#     all reasonable efforts to protect the confidentiality thereof, and to
#     use this information only in connection with your use of Broadcom
#     integrated circuit products.
# 
#  2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
#     AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
#     WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
#     RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND
#     ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT,
#     FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR
#     COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE
#     TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF USE OR
#     PERFORMANCE OF THE SOFTWARE.
# 
#  3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
#     ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
#     INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY
#     WAY RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN
#     IF BROADCOM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES;
#     OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE
#     SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE LIMITATIONS
#     SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY
#     LIMITED REMEDY.
# :>

[PMD calibration data]
#please don't delete any of the file lines or change the file format

# calibration mode:
# 1 = RX
# 2 = TX
# 3 = RX+TX (default)
cal_mode=3

#the value of the constant attenuation between the onu to opm
onu_to_tx_att_db=6.6
#the value of the attenuation in db between the opm and the onu rx path
onu_to_rx_opm_att_db=0
#to obtain -27dbm used in rssi calibration 
olt_to_onu_att1_db=19.74  
#to obtain -30dbm used in LOS calibration  
olt_to_onu_att2_db=22.74

# calibrate apd diode voltage: 1-yes / 0-no
cal_apd=0
# calibrate duty cycle distortion: 1-yes / 0-no (if fw support retiming set it to 0)
cal_dcd=0

#calibration in PRBS mode
cal_prbs_mode=1

# set calibration LOS type: lia_los / rssi_los (depends on fw support, rssi-los is much more accurate and robust)
los_type=rssi_los

#(*)setting calibration values
# apd_vbr_rssi:
#    target APD current at diode breakdown voltage, defined as raw RSSI value
#    default is 0.0285 (approximatly equivalent to 50uA)
# apd_vol_step:
#    step down value is how much to subtract from obtained APD break-down voltage in volts.
#    result apd voltage is used in calculating apd temperature to voltage conversion
# apd_vol_step:
#    apd regulator step resultion in Volts,
#    the reference design, feedback network defines this value as 47.5mV
# apd_vbr_coeff_high_temp:
#    apd vbr temperature coefficent in high temperature range (e.g. 25C to 85C)
# apd_vbr_coeff_low_temp:
#    apd vbr temperature coefficent in low temperature range (e.g. -40C to 25C)
# apd_vbr_temp_boundary:
#    temperature point defining the boundary between vbr temperature coefficents low and high (e.g. 25C)
apd_vbr_rssi=0.0285
apd_step_down_voltage=3
apd_vol_step=0.0475
apd_vbr_coeff_high_temp=0.08
apd_vbr_coeff_low_temp=0.11
apd_vbr_temp_boundary=25

# mpd_level default: 1800
# mpd_level_value:1600
max_mpd_level_value=1600
min_mpd_level_value=1000

# maximum allowed bias and modulation current to meet optical average power and extinction ratio targets
# (derived from BOSA spec - Ith, SE @ room temperature)
# biasctl range:0-4095 (0-80mA nominally), to allow any value set max_biasctl to 4095
# modctl range:0-2047 (0-80mA nominally), to allow any value set max_modctl to 2047
max_biasctl=2047
max_modctl=1600


# minimum allowed optical power [uW] after completing 1st step calibration of bias current.
# after 1st step bias current should be larger than Ith, to allow any value set the parameter to zero.
min_optical_power=20

# maximum and minimum eyesafety threshold limits.
# threshold range is 0-158. the limits shouuld allow some margin for temperature variation
# to allow any value set min threshold to 0, and max threshold to 158
max_eyesafety_thr=128
min_eyesafety_thr=16

# maximum and minimum rogue dark level limits.
# threshold range is 0-158. the limits shouuld allow some margin for temperature variation
# to allow any value set min threshold to 0, and max threshold to 158
max_rogue_dark_level=128
min_rogue_dark_level=0

#rssi-los parameters (used only if los_type==rssi-los):
# los assert threshold [dBm]
# los de-assert threshold [dBm]
# to avoid false assert/de-assert indication keep thresholds difference at least 2dB
los_assert_th_op_dbm=-35
los_deassert_th_op_dbm=-32

#avrg power dBm
avrg_power=2.5

#extintion ration target default 13dB
er_target_value=12.5

#determine whether to run extinction ratio or not 
run_extinction_ratio=1

#Level0 compensation parameters (use decimal values)
tracking_compensation_enable0=1
tracking_compensation_enable1=1
tracking_compensation_coeff1_q8=0
tracking_compensation_coeff2_q8=0

# board type:
#       ERROR: BORAD TYPE NOT DETERMINE = 0
#       FHBB = 1
#       FHBBST = 2
#       68910 GPON = 3
#       68910 XGPON = 4
#       6836 GPON = 5
#       63158 GPON = 6
#       6846 GPON = 7
#       6836 GPON and DCA 1.25G filter = 8
#       6878 GPON and DCA 1.25G filter = 9
board_type=0

# thermistor type:
#       1 = Vishay  NTHS0603N01N1003FE
#       2 = TDK  	NTCG104EF104FT1X
#		3 = MURATA  NCP15WF104F03RC
thermistor_type=2


# gpon: tx=1310nm, rx=1490nm
# xgpon: tx=1270nm, rx=1577nm
tx_wavelength_nm=1310
rx_wavelength_nm=1490

#optical power meter address
#opm_type:thorlabs
#tx_opm_address:USB0::0x1313::0x8072::P2008651::0::INSTR
#rx_opm_address:USB0::0x1313::0x8072::P2008653::0::INSTR
opm_type=keysight
tx_opm_address=GPIB0::14::INSTR::CH1
rx_opm_address=GPIB0::14::INSTR::CH2

#attenuator address
attenuator_address=GPIB0::9::INSTR
#attenuator_address:PROLOGIX::GPIB9
#attenuator_address:GOLIGHT

#DCA address
dca_address=TCPIP0::10.189.13.220::inst0::INSTR

