#
# d11shm.tpl  make file - Geneates d11 shm files
#
# $Copyright (C) 2002-2004 Broadcom Corporation$
# <<Broadcom-WL-IPTag/Proprietary:>>
# $Id: d11shm.tpl $
# comments for M_COREMASK_xxx:
# Txcore Mask related parameters 5 locations (BPHY, OFDM, 1-streams ~ 3-Streams) for WOWL
# The base address is different than normal ucode(offset is the same), but same name
FEATURE_BEGIN[common_base]
	M_SSID
	M_PRS_FRM_BYTESZ
	M_SSID_BYTESZ
	M_PMQADDINT_THSD
	M_RT_BBRSMAP_A		#Rate table offsets
	M_RT_BBRSMAP_B
	M_FIFOSIZE0			# TX fifo sizes
	M_FIFOSIZE1
	M_FIFOSIZE2
	M_FIFOSIZE3
	M_MBURST_TXOP		# max frameburst TXOP in unit of us
	M_MBURST_SIZE		# max frames in a frameburst
	M_MODE_CORE			#Phy mode setting for ucode
	M_WLCX_CONFIG		#bitmap for the feature
	M_WLCX_GPIO_CONFIG	#GPIO to be used for 5357/43235
	M_DOT11_DTIMPERIOD
	M_TIMBC_OFFSET		# TIMBC offset value: wnm
	M_CCKBOOST_ADJ
	M_EDCF_BLKS
	M_EDCF_QINFO1
	M_EDCF_QINFO2
	M_EDCF_QINFO3
	M_EDCF_BOFF_CTR
	M_LNA_ROUT
	M_RXGAIN_HI
	M_RXGAIN_LO
	M_RXGAINOVR2_VAL
	M_LPFGAIN_HI
	M_LPFGAIN_LO
	M_CUR_TXF_INDEX
	M_COREMASK_BLK
	M_COREMASK_BPHY
	M_COREMASK_BFM
	M_COREMASK_BFM1
	M_COREMASK_BTRESP
	M_TXPWR_BLK		# txpower overrides
	M_PS_MORE_DTIM_TBTT		# pm
	M_POSTDTIM0_NOSLPTIME	# pm
	M_BCMC_FID
	M_AMT_INFO_PTR
	M_PRS_MAXTIME		# Probe response related parameters
	M_PRETBTT
	M_BCN_TXTSF_OFFSET	# beacon related parameters
	M_TIMBPOS_INBEACON	# beacon related parameters
	M_AGING_THRSH		# max time waiting for medium before tx
	M_SYNTHPU_DELAY		# pre-wakeup for synthpu, default: 500
	M_PHYVER
	M_PHYTYPE
	M_MAX_ANTCNT		# antenna swap threshold
	M_MACHW_VER			# Location where the ucode expects the corerev
	M_MACHW_CAP_L		# Location where the ucode expects the MAC capabilities
	M_MACHW_CAP_H		# Location where the ucode expects the MAC capabilities
	M_SFRMTXCNTFBRTHSD	# Beacon-related parameters
	M_LFRMTXCNTFBRTHSD	# Beacon-related parameters
	M_TXDC_BYTESZ		# ACK/CTS related params
	M_TXFL_BMAP			# selectively flushing of transmit fifo's
	M_JSSI_AUX
	M_DOT11_SLOT		# stf/PS-mode related parameters
	M_DUTY_STRTRATE
	M_SECRSSI0_MIN
	M_SECRSSI1_MIN
	M_MIMO_ANTSEL_RXDFLT	#Antenna Diversity Testing
	M_MIMO_ANTSEL_TXDFLT
	M_ANTSEL_CLKDIV
	M_BOM_REV_MAJOR	# PSM SHM variable offsets
	M_BOM_REV_MINOR
	M_HOST_FLAGS	# Host flags to turn on ucode options
	M_HOST_FLAGS2	# Host flags to turn on ucode options
	M_HOST_FLAGS3	# Host flags to turn on ucode options
	M_HOST_FLAGS4	# Host flags to turn on ucode options
	M_HOST_FLAGS5	# Host flags to turn on ucode options
	M_REV_L
	M_REV_H
	M_UCODE_FEATURES
	M_ULP_STATUS
	M_EDCF_QINFO1_OFFSET
	M_MYMAC_ADDR
	M_UTRACE_SPTR
	M_UTRACE_EPTR
	M_TXFRAME_CNT
	M_TXAMPDU_CNT
	M_RXSTRT_CNT
	M_RXCRSGLITCH_CNT
	M_BPHYGLITCH_CNT
	M_RXBADFCS_CNT
	M_RXBADPLCP_CNT
	M_RXBPHY_BADPLCP_CNT
	M_AC_TXLMT_BLK
	M_MAXRXFRM_LEN
	M_MAXRXMPDU_LEN
	M_RXCORE_STATE
	M_ASSERT_REASON
	M_WRDCNT_RXF1OVFL_THRSH
	M_WRDCNT_RXF0OVFL_THRSH
	M_NCAL_ACTIVE_CORES
	M_NCAL_CFG_BMP
	M_NCAL_RFCTRLOVR_0
	M_NCAL_RXGAINOVR_0
	M_NCAL_RXLPFOVR_0
	M_NCAL_RXGAIN_LO
	M_NCAL_LPFGAIN_LO
	M_NCAL_RXGAIN_HI
	M_NCAL_LPFGAIN_HI
	M_NCAL_RFCTRLOVR_VAL
	M_BSR_BLK
	M_SEMAPHORE_BSR
	M_BSR_ALLTID_SET0
	M_BSR_ALLTID_SET1
	M_ACKPWRTBL_R0_1
	M_ACKPWRTBL_R0_2
	M_ACKPWRTBL_R1_0
	M_ACKPWRTBL_R1_1
	M_ACKPWRTBL_R2_0
	M_ACKPWRTBL_R2_1
	M_ACKPWRTBL_R3_0
	M_ACKPWRTBL_R3_1
	M_ACKPWRTBL_R4_0
	M_ACKPWRTBL_R4_1
	M_ACKPWRTBL_R5_0
	M_ACKPWRTBL_R5_1
	M_ACKPWRTBL_R6_0
	M_ACKPWRTBL_R6_1
	M_ACKPWRTBL_R7_0
	M_ACKPWRTBL_R7_1
	M_ACKPWRTBL_R8_0
	M_ACKPWRTBL_R8_1
	M_ACK_2GCM_NUMB
	M_BTACK_2GCM_NUMB
	M_CUR_ACK_OFST
	M_TXPWRCAP_C0
	M_TXPWRCAP_C1
	M_TXPWRCAP_C2
	M_TXPWRCAP_C0_FS
	M_TXPWRCAP_C1_FS
	M_TXPWRCAP_C2_FS
	M_TXPWRCAP_C0_FSANT
	M_TXPWRCAP_BT_C0
	M_TXPWRCAP_BT_C1
	M_TXPWRCAP_BT_C2
	M_TDMTX_RSSI_THR
	M_TDMTX_TXPWRBOFF
	M_TDMTX_TXPWRBOFF_DT
	M_CCA_MEASINTV_L
	M_CCA_MEASINTV_H
	M_CCA_MEASBUSY_L
	M_CCA_MEASBUSY_H
FEATURE_END
FEATURE_BEGIN[proxd]
	M_TOF_BLK_PTR			#Block Pointer
	M_TOF_CMD_OFFSET		#command txed from fw to ucode
	M_TOF_RSP_OFFSET		#response from ucode to fw
	M_TOF_CHNSM_0_OFFSET	#Channel smoothing 0
	M_TOF_DOT11DUR_OFFSET	#802.11 reseved dur value
	M_TOF_PHYCTL0_OFFSET	#PHYCTL0 value
	M_TOF_PHYCTL1_OFFSET	#PHYCTL1 value
	M_TOF_PHYCTL2_OFFSET	#PHYCTL2 value
	M_TOF_LSIG_OFFSET		#LSIG value
	M_TOF_VHTA0_OFFSET		#VHTA0 value
	M_TOF_VHTA1_OFFSET		#VHTA1 value
	M_TOF_VHTA2_OFFSET		#VHTA2 value
	M_TOF_VHTB0_OFFSET		#VHTB0 value
	M_TOF_VHTB1_OFFSET		#VHTB1 value
	M_TOF_AMPDU_CTL_OFFSET	#AMPDU_CTL value
	M_TOF_AMPDU_DLIM_OFFSET	#AMPDU_DLIM value
	M_TOF_AMPDU_LEN_OFFSET	#AMPDU length
	M_TOF_FLAGS_OFFSET	#Flag to process FTM frames
        M_TOF_AVB_ACK_ON
        M_TOF_AVB_BLK
        M_TOF_AVB_BLK_IDX
        M_TOF_DBG_BLK_OFFSET
        M_TOF_DBG1_OFFSET
        M_TOF_DBG2_OFFSET
        M_TOF_DBG3_OFFSET
        M_TOF_DBG4_OFFSET
        M_TOF_DBG5_OFFSET
        M_TOF_DBG6_OFFSET
        M_TOF_DBG7_OFFSET
        M_TOF_DBG8_OFFSET
        M_TOF_DBG9_OFFSET
        M_TOF_DBG10_OFFSET
        M_TOF_DBG11_OFFSET
        M_TOF_DBG12_OFFSET
        M_TOF_DBG13_OFFSET
        M_TOF_DBG14_OFFSET
        M_TOF_DBG15_OFFSET
        M_TOF_DBG16_OFFSET
        M_TOF_DBG17_OFFSET
        M_TOF_DBG18_OFFSET
        M_TOF_DBG19_OFFSET
        M_TOF_DBG20_OFFSET
FEATURE_END
FEATURE_BEGIN[mcnx]
	M_P2P_BLK_PTR
	M_P2P_PERBSS_BLK
	M_P2P_INTF_BLK
	M_ADDR_BMP_BLK_OFFSET
	M_P2P_INTR_BLK
	M_P2P_HPS
	M_P2P_HPS_OFFSET
	M_P2P_TSF_OFFSET_BLK
	M_P2P_GO_CHANNEL
	M_P2P_GO_IND_BMP
	M_P2P_PRETBTT_BLK
	M_P2P_TSF_DRIFT_WD0
	M_P2P_TXSTOP_T_BLK
FEATURE_END

FEATURE_BEGIN[p2p]
	M_SHM_BYT_CNT
FEATURE_END

FEATURE_BEGIN[mfgtest]
	M_MFGTEST_FRMCNT_LO	# Lower word of tx frmcnt/rx lostcnt
	M_MFGTEST_FRMCNT_HI	# Upper word of tx frmcnt/rx lostcnt
	M_MFGTEST_NUM		# PER test mode., old name: M_PKTENG_CTRL
	M_MFGTEST_IO1		# IFS for TX mode., old name: M_PKTENG_IFS
	M_RXSTATS_BLK_PTR	# PKTENG Rx Stats Block
	M_MFGTEST_UOTARXTEST
	M_MFGTEST_RXAVGPWR_ANT0
	M_MFGTEST_RXAVGPWR_ANT1
	M_MFGTEST_RXAVGPWR_ANT2
FEATURE_END

FEATURE_BEGIN[km]
	M_TKMICKEYS_PTR
	M_WAPIMICKEYS_PTR
	M_SECKEYS_PTR
	M_SECKINDX_PTR
	M_TKIP_TTAK_PTR
	M_SECKINDXALGO_BLK
	M_TKIP_TSC_TTAK
FEATURE_END

# shm location for TXBF
FEATURE_BEGIN[txbf]
	M_BFI_BLK
	M_BFI_REFRESH_THR
	M_BFI_NRXC
FEATURE_END

# macstat1 counters : corerev >= 40 only
FEATURE_BEGIN[macstat]
	M_PSM2HOST_STATS	# macstat counters
	M_PSM2HOST_EXT_PTR	# will be named in driver as M_UCODE_MACSTAT1_PTR
	M_UCODE_DBGST		# UCODE debug status
	M_BCN0_FRM_BYTESZ	# Bcn 0 template length
	M_BCN1_FRM_BYTESZ	# Bcn 1 template length
	M_DEBUGBLK_PTR
	M_TXERR_NOWRITE
	M_TXERR_REASON
	M_TXERR_REASON2
	M_TXERR_CTXTST
	M_TXERR_PCTL0
	M_TXERR_PCTL1
	M_TXERR_PCTL2
	M_TXERR_LSIG0
	M_TXERR_LSIG1
	M_TXERR_PLCP0
	M_TXERR_PLCP1
	M_TXERR_PLCP2
	M_TXERR_SIGB0
	M_TXERR_SIGB1
	M_TXERR_RXESTATS2
	M_TXNDPA_CNT
	M_TXNDP_CNT
	M_TXBFPOLL_CNT
	M_TXSF_CNT
	M_TXCWRTS_CNT
	M_TXCWCTS_CNT
	M_TXBFM_CNT
	M_RXNDPAUCAST_CNT
	M_RXNDPAMCAST_CNT
	M_RXBFPOLLUCAST_CNT
	M_BFERPTRDY_CNT
	M_RXSFUCAST_CNT
	M_RXCWRTSUCAST_CNT
	M_RXCWCTSUCAST_CNT
	M_RXDROP20S_CNT
	M_RX20S_CNT
	M_BTCX_RFACT_CTR_L
	M_MACSUSP_CNT
FEATURE_END

# MBSS shared memory address definitions; see [MultiBSSUcode] Twiki
FEATURE_BEGIN[mbssid]
	M_MBSSID_BLK
	M_MBS_BSSID0
	M_MBS_BSSID1
	M_MBS_BSSID2
	M_MBS_NBCN
	M_MBS_PRQBASE
	M_MBS_PRETBTT
	M_MBS_BSSIDNUM
	M_MBS_PIO_BCBMP
	M_MBS_PRS_TPLPTR
	M_MBS_PRSLEN_BLK
	M_MBS_BCFID_BLK
	M_MBS_SSIDLEN_BLK
	M_MBS_SSID_1
	M_PRQFIFO_RPTR
	M_PRQFIFO_WPTR
FEATURE_END

FEATURE_BEGIN[physim]
	M_RFLDO_ON_L
	M_RFLDO_ON_H
	M_PAPDOFF_MCS
	M_LPF_PASSIVE_RC_OFDM
	M_LPF_PASSIVE_RC_CCK
	M_SMPL_COL_BMP			#Trigger bitmap for sample collect
	M_SMPL_COL_CTL			#Sample collect type
	M_RT_DIRMAP_A
	M_RT_DIRMAP_B
	M_CTS_DURATION
	M_TSSI_0
	M_TSSI_1
	M_IFS_PRICRS		# see M_IFSCTL1 also
	M_TSSI_OFDM_0
	M_TSSI_OFDM_1
	M_CURCHANNEL		#Current channel number plus upper bits
	M_PWRIND_BLKS		#Index of attenuations used during ucode power control
	M_PWRIND_MAP0
	M_PWRIND_MAP1
	M_PWRIND_MAP2
	M_PWRIND_MAP3
	M_PWRIND_MAP4
	M_PWRIND_MAP5
	M_HWACI_STATUS
	M_HWACI_EN_IND
	M_FCBS_BLK
	M_FCBS_TEMPLATE_LENS
	M_FCBS_BPHY_CTRL
	M_FCBS_TEMPLATE_PTR
	M_AFEOVR_PTR		#XXX adress tone jammer WAR block
	M_RXGAININFO_ANT0_OFFSET
	M_RXAUXGAININFO_ANT0_OFFSET
	M_RADAR_REG
FEATURE_END

FEATURE_BEGIN[ulpphysim]
	M_RADIOPWRUP_PTR
	M_RADIOPWRDWN_PTR
	M_EXT_AVAIL3
	M_HOST_FLAGS6
	M_TXPWR_MAX
	M_TXPWR_CUR
	M_BCMC_TIMEOUT				#max time waiting for BCMC in PM
	M_BCMCROLL_TMOUT			#max time waiting for BCMC MoreData=0 in PM
	M_TXPWR_M
	M_TXPWR_TARGET
	M_USEQ_PWRUP_PTR
	M_USEQ_PWRDN_PTR
	M_SLP_RDY_INT
	M_TPCNNUM_INTG_LOG2
	M_TSSI_SENS_LMT1
	M_TSSI_SENS_LMT2
FEATURE_END
FEATURE_BEGIN[btcx]
	M_BTCX_BLK_PTR
	M_BTCX_PRED_PER
	M_BTCX_LAST_SCO
	M_BTCX_LAST_SCO_H
	M_BTCX_BLE_SCAN_GRANT_THRESH
	M_BTCX_NEXT_SCO
	M_BTCX_REQ_START
	M_BTCX_REQ_START_H
	M_BTCX_LAST_DATA
	M_BTCX_BT_TYPE
	M_BTCX_ECI0
	M_BTCX_ECI1
	M_BTCX_ECI2
	M_BTCX_ECI3
	M_BTCX_LAST_A2DP
	M_BTCX_PRI_MAP_LO
	M_BTCX_HOLDSCO_LIMIT_OFFSET
	M_BTCX_SCO_GRANT_HOLD_RATIO_OFFSET
	M_BTCX_PRED_COUNT
	M_BTCX_PROT_RSSI_THRESH_OFFSET
	M_BTCX_PROT_RSSI_THRESH
	M_BTCX_HOST_FLAGS_OFFSET
	M_BTCX_HOST_FLAGS
	M_BTCX_RSSI
	M_BTCX_BT_TXPWR
	M_BTCX_HIGH_THRESH
	M_BTCX_LOW_THRESH
	M_BTCX_CONFIG_OFFSET
	M_BTCX_CONFIG
	M_BTCX_NUM_TASKS_OFFSET
	M_BTCX_NUM_TASKS
	M_BTCXDBG_BLK
	M_BTCX_RFSWMSK_BT_OFFSET
	M_BTCX_RFSWMSK_BT
	M_BTCX_RFSWMSK_WL_OFFSET
	M_BTCX_RFSWMSK_WL
	M_BTCX_AGG_OFF_BM
	M_BTCX_PKTABORTCTL_VAL
	M_BTCX_BT_TASKS_BM_LOW
	M_BTCX_BT_TASKS_BM_HI
	M_BTCX_ABORT_CNT
	M_BTCX_LATENCY_CNT
	M_BTCX_HOST_FLAGS2_OFFSET
	M_BTCX_HOST_FLAGS2
	M_BTCX_IBSS_TSF_L
	M_BTCX_IBSS_TSF_ML
	M_BTCX_IBSS_TSF_SCO_L
	M_BTCX_SUCC_PM_PROTECT_CNT
	M_BTCX_SUCC_CTS2A_CNT
	M_BTCX_WLAN_TX_PREEMPT_CNT
	M_BTCX_WLAN_RX_PREEMPT_CNT
	M_BTCX_APTX_AFTER_PM_CNT
	M_BTCX_PERAUD_CUMU_GRANT_CNT
	M_BTCX_PERAUD_CUMU_DENY_CNT
	M_BTCX_A2DP_CUMU_GRANT_CNT
	M_BTCX_A2DP_CUMU_DENY_CNT
	M_BTCX_SNIFF_CUMU_GRANT_CNT
	M_BTCX_SNIFF_CUMU_DENY_CNT
FEATURE_END

#LTECX shares BTCX shmem block
FEATURE_BEGIN[ltecx]
	M_LTECX_FLAGS
	M_LTECX_STATE
	M_LTECX_HOST_FLAGS
	M_LTECX_TX_LOOKAHEAD_DUR
	M_LTECX_PROT_ADV_TIME
	M_LTECX_WCI2_TST_LPBK_NBYTES_TX
	M_LTECX_WCI2_TST_LPBK_NBYTES_ERR
	M_LTECX_WCI2_TST_LPBK_NBYTES_RX
	M_LTECX_RX_REAGGR
	M_LTECX_ACTUALTX_DURATION
	M_LTECX_CRTI_MSG
	M_LTECX_CRTI_INTERVAL
	M_LTECX_CRTI_REPEATS
	M_LTECX_WCI2_TST_MSG
	M_LTECX_RXPRI_THRESH
	M_LTECX_MWSSCAN_BM_LO
	M_LTECX_MWSSCAN_BM_HI
	M_LTECX_PWRCP_C0
	M_LTECX_PWRCP_C0_FS
	M_LTECX_PWRCP_C0_FSANT
	M_LTECX_PWRCP_C1
	M_LTECX_PWRCP_C1_FS
	M_LTECX_FS_OFFSET
	M_LTECX_TXNOISE_CNT
	M_LTECX_NOISE_DELTA
	M_LTECX_TYPE4_TXINHIBIT_DURATION
	M_LTECX_TYPE4_NONE_ZERO_CNT
	M_LTECX_TYPE4_TIMEOUT_CNT
	M_LTECX_RXPRI_DURATION
	M_LTECX_RXPRI_CNT
	M_LTECX_TYP6_DURATION
	M_LTECX_TYP6_CNT
	M_LTECX_TS_PROT_FRAME_CNT
	M_LTECX_TS_GRANT_CNT
	M_LTECX_TS_GRANT_TIME_DUR
FEATURE_END

FEATURE_BEGIN[ccastat]
	M_CCASTATS_PTR
	M_CCA_STATS_BLK
	M_CCA_TXDUR_L_OFFSET
	M_CCA_TXDUR_H_OFFSET
	M_CCA_INBSS_L_OFFSET
	M_CCA_INBSS_H_OFFSET
	M_CCA_OBSS_L_OFFSET
	M_CCA_OBSS_H_OFFSET
	M_CCA_NOCTG_L_OFFSET
	M_CCA_NOCTG_H_OFFSET
	M_CCA_NOPKT_L_OFFSET
	M_CCA_NOPKT_H_OFFSET
	M_MAC_SLPDUR_L_OFFSET
	M_MAC_SLPDUR_H_OFFSET
	M_CCA_TXOP_L_OFFSET
	M_CCA_TXOP_H_OFFSET
	M_CCA_GDTXDUR_L_OFFSET
	M_CCA_GDTXDUR_H_OFFSET
	M_CCA_BDTXDUR_L_OFFSET
	M_CCA_BDTXDUR_H_OFFSET
	M_CCA_WIFI_L_OFFSET
	M_CCA_WIFI_H_OFFSET
	M_CCA_EDCRSDUR_L_OFFSET
	M_CCA_EDCRSDUR_H_OFFSET
	M_CCA_TXDUR_L
	M_CCA_TXDUR_H
	M_CCA_INBSS_L
	M_CCA_INBSS_H
	M_CCA_OBSS_L
	M_CCA_OBSS_H
	M_CCA_NOCTG_L
	M_CCA_NOCTG_H
	M_CCA_NOPKT_L
	M_CCA_NOPKT_H
	M_MAC_SLPDUR_L
	M_MAC_SLPDUR_H
	M_CCA_TXOP_L
	M_CCA_TXOP_H
	M_CCA_GDTXDUR_L
	M_CCA_GDTXDUR_H
	M_CCA_BDTXDUR_L
	M_CCA_BDTXDUR_H
	M_CCA_RXPRI_LO
	M_CCA_RXPRI_HI
	M_CCA_RXSEC20_LO
	M_CCA_RXSEC20_HI
	M_CCA_RXSEC40_LO
	M_CCA_RXSEC40_HI
	M_CCA_RXSEC80_LO
	M_CCA_RXSEC80_HI
	M_CCA_SUSP_L
	M_CCA_SUSP_H
	M_CCA_WIFI_L
	M_CCA_WIFI_H
	M_CCA_EDCRSDUR_L
	M_CCA_EDCRSDUR_H
	M_SECRSSI0
	M_SECRSSI1
	M_SECRSSI2
	M_SISO_RXDUR_L
	M_SISO_RXDUR_H
	M_SISO_TXOP_L
	M_SISO_TXOP_H
	M_MIMO_RXDUR_L
	M_MIMO_RXDUR_H
	M_MIMO_TXOP_L
	M_MIMO_TXOP_H
	M_MIMO_TXDUR_1X_L
	M_MIMO_TXDUR_1X_H
	M_MIMO_TXDUR_2X_L
	M_MIMO_TXDUR_2X_H
	M_MIMO_TXDUR_3X_L
	M_MIMO_TXDUR_3X_H
	M_SISO_SIFS_L
	M_SISO_SIFS_H
	M_MIMO_SIFS_L
	M_MIMO_SIFS_H
	M_CCA_TXNODE0_L_OFFSET
	M_CCA_TXNODE0_H_OFFSET
	M_CCA_RXNODE0_L_OFFSET
	M_CCA_RXNODE0_H_OFFSET
	M_CCA_XXOBSS_L_OFFSET
	M_CCA_XXOBSS_H_OFFSET
	M_MESHCCA_STATS_BLK
	M_MESHCCA_TXNODE0_OFFSET
	M_MESHCCA_RXNODE0_OFFSET
	M_MESHCCA_OBSSNODE_OFFSET
	M_MESHCCA_TXNODE0
	M_MESHCCA_RXNODE0
	M_MESHCCA_OBSSNODE
FEATURE_END

FEATURE_BEGIN[ampdu]
	M_TXFS_PTR
	M_AMP_STATS_PTR
	M_MIMO_MAXSYM
	M_WATCHDOG_8TU
FEATURE_END

FEATURE_BEGIN[btamp]
	M_BTAMP_GAIN_DELTA	# offset to the target txpwr
FEATURE_END

# following is put for shm's present in rev > 40 but NOT present in rev < 40.
FEATURE_BEGIN[rev_ge_40]
	M_BCN_TXPCTL0
	M_BCN_TXPCTL1
	M_BCN_TXPCTL2
	M_TXDUTY_RATIOX16_CCK	# idle busy ratio to duty_cycle requirement
	M_TXDUTY_RATIOX16_OFDM	# idle busy ratio to duty_cycle requirement
FEATURE_END
# following is put for shms present in rev < 40 but NOT present in rev > 40.
# note for M_LCNXN_SWCTRL_MASK : # PR 108019: CLB bug WAR - clb_rf_sw_ctrl_mask_ctrl mask -
#	- for WLAN to defer control to BT

FEATURE_BEGIN[rev_lt_40]
	M_BCN_PCTLWD
	M_BCN_PCTL1WD
	M_SWDIV_SWCTRL_REG
	M_SWDIV_PREF_ANT
	M_SWDIV_TX_PREF_ANT
	M_LCNXN_SWCTRL_MASK # see above note
	M_4324_RXTX_WAR_PTR
	M_TX_MODE_0xb0_OFFSET
	M_TX_MODE_0x14d_OFFSET
	M_TX_MODE_0xb1_OFFSET
	M_TX_MODE_0x14e_OFFSET
	M_TX_MODE_0xb4_OFFSET
	M_TX_MODE_0x151_OFFSET
	M_RX_MODE_0xb0_OFFSET
	M_RX_MODE_0x14d_OFFSET
	M_RX_MODE_0xb1_OFFSET
	M_RX_MODE_0x14e_OFFSET
	M_RX_MODE_0xb4_OFFSET
	M_RX_MODE_0x151_OFFSET
	M_CHIP_CHECK_OFFSET
	M_CTXPRS_BLK
	M_RADIO_PWR
	M_IFSCTL1	# XXX address of stored default ifs_ctl1 value. M_IFS_PRICRS for ge40
	M_TX_IDLE_BUSY_RATIO_X_16_CCK	# idle busy ratio to duty_cycle requirement
	M_TX_IDLE_BUSY_RATIO_X_16_OFDM	# idle busy ratio to duty_cycle requirement
	M_RSP_PCTLWD
	M_BCN_POWER_ADJUST
	M_PRS_POWER_ADJUST
FEATURE_END

FEATURE_BEGIN[bcntrim]
	M_BCNTRIM_BLK				#Beacon trim feature definition
	M_BCNTRIM_PER_OFFSET			#Enable Disable Beacon Trim
	M_BCNTRIM_TIMEND_OFFSET			#Waiting time for TIM IE to end
	M_BCNTRIM_TSFLMT_OFFSET			#TSF tolerance value(usecs)
	M_BCNTRIM_CNT_OFFSET			#PSM's local beacon trim counter
	M_BCNTRIM_RSSI_OFFSET			#Partial beacon RSSI
	M_BCNTRIM_CHAN_OFFSET			#Partial beacon channel
	M_BCNTRIM_SNR_OFFSET			#Partial beacon SNR
	M_BCNTRIM_CUR_OFFSET			#Count from 0 to N received
	M_BCNTRIM_PREVLEN_OFFSET		#Beacon length excluding the TIM IE
	M_BCNTRIM_TIMLEN_OFFSET			#TIM IE Length
	M_BCNTRIM_RXMBSS_OFFSET			#Total beacons
	M_BCNTRIM_TIMNOTFOUND_OFFSET		#beacons not trimmed due to TIM missing
	M_BCNTRIM_CANTRIM_OFFSET		#Num of beacons which can be trimmed
	M_BCNTRIM_LENCHG_OFFSET			#beacons not trimmed due to length change
	M_BCNTRIM_TSFDRF_OFFSET			#beacons not trimmed due to large TSF delta
	M_BCNTRIM_TIMBITSET_OFFSET		#beacons not trimmed due to TIM bit set
	M_BCNTRIM_WAKE_OFFSET			#beacons not trimmed due to wake bit set
	M_BCNTRIM_SSID_OFFSET			#beacons not trimmed due to SSID length or value change
	M_BCNTRIM_DTIM_OFFSET			#beacons not trimmed due to DTIM change
	M_BCNTRIM_SSIDBLK_OFFSET		# 17 words for SSID TLV
FEATURE_END

FEATURE_BEGIN[rev_sslp_lt_40]
	M_PHY_NOISE
	M_RSSI_LOCK_OFFSET
	M_RSSI_LOGNSAMPS_OFFSET
	M_RSSI_NSAMPS_OFFSET
	M_RSSI_IQEST_EN_OFFSET
	M_RSSI_BOARDATTEN_DBG_OFFSET
	M_RSSI_IQPWR_DBG_OFFSET
	M_RSSI_IQPWR_DB_DBG_OFFSET
	M_NOISE_IQPWR
	M_NOISE_IQPWR_OFFSET
	M_NOISE_IQPWR_DB_OFFSET
	M_NOISE_LOGNSAMPS
	M_NOISE_LOGNSAMPS_OFFSET
	M_NOISE_NSAMPS
	M_NOISE_NSAMPS_OFFSET
	M_NOISE_IQEST_EN_OFFSET
	M_NOISE_IQEST_PENDING
	M_NOISE_IQEST_PENDING_OFFSET
	M_RSSI_IQEST_PENDING_OFFSET
	M_NOISE_LTE_ON
	M_NOISE_LTE_IQPWR_DB_OFFSET
	M_SSLPN_RSSI_0_OFFSET
	M_SSLPN_SNR_0_logchPowAccOut_OFFSET
	M_SSLPN_SNR_0_errAccOut_OFFSET
	M_SSLPN_RSSI_1_OFFSET
	M_SSLPN_SNR_1_logchPowAccOut_OFFSET
	M_SSLPN_SNR_1_errAccOut_OFFSET
	M_SSLPN_RSSI_2_OFFSET
	M_SSLPN_SNR_2_logchPowAccOut_OFFSET
	M_SSLPN_SNR_2_errAccOut_OFFSET
	M_SSLPN_RSSI_3_OFFSET
	M_SSLPN_SNR_3_logchPowAccOut_OFFSET
	M_SSLPN_SNR_3_errAccOut_OFFSET
	M_RSSI_QDB_0_OFFSET
	M_RSSI_QDB_1_OFFSET
	M_RSSI_QDB_2_OFFSET
	M_RSSI_QDB_3_OFFSET
FEATURE_END

FEATURE_BEGIN[wowl]
	M_WOWL_TEST_CYCLE  # Time to wakeup in seconds
	M_WOWL_TMR_L       # lower TSF LSB to be passed to ucode
	M_WOWL_TMR_ML      # Lower TSF MSB to be passed to ucode
	M_KEYRC_LAST       # Last good key replay counter
	M_NETPAT_BLK_PTR   # address for location of pattern 1
	M_WOWL_GPIOSEL     #GPIO Sel for 11AC Chips
	M_NETPAT_NUM
	M_AESTABLES_PTR
	M_AID_NBIT
	M_HOST_WOWLBM
	M_GROUPKEY_UPBM   #Last rotated key index
	M_WOWL_OFFLOADCFG_PTR
	M_CTX_GTKMSG2     #Tx descriptor for offloaded templates
	M_TXPHYERR_CNT
	M_SECSUITE
	M_TSCPN_BLK
	M_WAKEEVENT_IND
	M_EAPOLMICKEY_BLK
	M_RXFRM_SRA0
	M_RXFRM_SRA1
	M_RXFRM_SRA2
	M_RXFRM_RA0
	M_RXFRM_RA1
	M_RXFRM_RA2
	M_TXPSPFRM_CNT
	M_WOWL_NOBCN
FEATURE_END

FEATURE_BEGIN[bcmulp]
	M_DRVR_UCODE_IF_PTR
	M_ULP_FEATURES_OFFSET
	M_DRIVER_BLOCK_OFFSET
	M_CRX_BLK          #rxstatus corr to pkt in M_RXFRM_BASE_ADDR
	M_RXFRM_BASE_ADDR  #location of Rxpkt received which caused ULP bailout
	M_SAVERESTORE_4335_BLK
	M_ILP_PER_H_OFFSET
	M_ILP_PER_L_OFFSET
	M_DRIVER_BLOCK
	M_FCBS_DS1_MAC_INIT_BLOCK_OFFSET
	M_FCBS_DS1_PHY_RADIO_BLOCK_OFFSET
	M_FCBS_DS1_RADIO_PD_BLOCK_OFFSET
	M_FCBS_DS1_EXIT_BLOCK_OFFSET
	M_FCBS_DS0_RADIO_PU_BLOCK_OFFSET
	M_FCBS_DS0_RADIO_PD_BLOCK_OFFSET
	M_ULP_WAKE_IND
	M_ILP_PER_H
	M_ILP_PER_L
	M_DS1_CTRL_SDIO_PIN
	M_DS1_CTRL_SDIO
	M_RXBEACONMBSS_CNT
	M_FRRUN_LBCN_CNT
	M_FCBS_DS0_RADIO_PU_BLOCK
	M_FCBS_DS0_RADIO_PD_BLOCK
FEATURE_END

FEATURE_BEGIN[tsync]
	M_TS_SYNC_GPIO
	M_TS_SYNC_TSF_L
	M_TS_SYNC_TSF_ML
	M_TS_SYNC_AVB_L
	M_TS_SYNC_AVB_H
	M_TS_SYNC_PMU_L
	M_TS_SYNC_PMU_H
	M_TS_SYNC_TXTSF_ML
	M_TS_SYNC_GPIOMINDLY
	M_TS_SYNC_GPIOREALDLY
FEATURE_END

FEATURE_BEGIN[ops]
	M_OPS_MODE		# to enable/disable
	M_OPS_RSSI_THRSH	# update rssi threshold (bcn rssi -10dbm)
	M_OPS_MAX_LMT		# max ops duration threshold. 12500 usec default
	M_OPS_HIST		# these are total 5 SHM for 5 histogram bins.
	M_OPS_LIGHT_L		# lower 16bit of partial ops duration
	M_OPS_LIGHT_H		# upper 16bit of partial ops duration
	M_OPS_FULL_L		# lower 16bit of full ops duration
	M_OPS_FULL_H		# upper 16bit of full ops duration
	M_OPS_NAV_CNT		# number of ops using NAV
	M_OPS_PLCP_CNT		# number of ops using PLCP
	M_OPS_RSSI_CNT		# number of ops missed due to rssi threshold
	M_OPS_MISS_CNT		# number of ops missed due to insufficient duration
	M_OPS_MAXLMT_CNT	# number of ops missed due to max duration limit
	M_OPS_MYBSS_CNT		# number of ops from mybss
	M_OPS_OBSS_CNT		# number of ops from obss
	M_OPS_WAKE_CNT		# number of ops missed due to wake bit set
	M_OPS_BCN_CNT		# number of ops missed owing to receive bcn
FEATURE_END

# following is put for shm's present in rev >= 64
FEATURE_BEGIN[rev_ge_64]
	M_UCODE_MACSTAT
	M_UCODE_MACSTAT1_PTR
	M_SYNTHPU_DLY
	MX_PSM_SOFT_REGS
	MX_BOM_REV_MAJOR
	MX_BOM_REV_MINOR
	MX_UCODE_DATE
	MX_UCODE_TIME
	MX_UCODE_DBGST
	MX_WATCHDOG_8TU
	MX_MACHW_VER
	MX_PHYVER
	MX_PHYTYPE
	MX_HOST_FLAGS0
	MX_HOST_FLAGS1
	MX_HOST_FLAGS2
	MX_UCX2R_FLAGS
	MX_BFI_BLK
	MX_NDPPWR_TBL	# to be removed
	MX_VMU_NDPPWR_TBL
	MX_HMU_NDPPWR_TBL
	MX_MUSND_PER
	MX_UTRACE_SPTR
	MX_UTRACE_EPTR
	M_AGGMPDU_HISTO
	M_AGGSTOP_HISTO
	M_MBURST_HISTO
	M_TXBCN_DUR
	M_PHYPREEMPT_VAL
FEATURE_END

# following is put for shm's present in rev >= 80
FEATURE_BEGIN[rev_ge_80]
	M_BCN_TXPCTL_PTR
	M_RXTRIG_CMNINFO
	M_RXTRIG_USRINFO
	M_TXERR_CTRLWD_DBGINFO
	M_TXERR_UCODETX_TS
	M_TXERR_HWTX_TS
	M_TXERR_UCODERR_TS
	M_LOOP_ID
FEATURE_END

# following is put for shm's present in rev >= 128
FEATURE_BEGIN[rev_ge_128]
	M_TXERR_PHYSTS
	M_TXERR_REASON0
	M_TXERR_REASON1
	M_TXERR_TXDUR
	M_TXERR_PCTLEN
	M_TXERR_PCTL4
	M_TXERR_PCTL9
	M_TXERR_PCTL10
	M_TXERR_CCLEN
	M_TXERR_TXBYTES_L
	M_TXERR_TXBYTES_H
	M_TXERR_UNFLSTS
	M_TXERR_USR
	MX_RTMEM_RDY
	M_RXTRIG_MYAID_CNT
	M_RXTRIG_RAND_CNT
	M_RXSWRST_CNT
	M_RXSFCQI_CNT
	M_NDPAUSR_CNT
	M_BFD_DONE_CNT
	M_BFD_FAIL_CNT
	M_RXPFFLUSH_CNT
	M_RXFLUCMT_CNT
	M_RXFLUOV_CNT
	MX_HEMSCH_BLKS
	MX_HEMSCH0_BLK
	MX_HEMSCH0_SIGA
	MX_HEMSCH0_PCTL0
	MX_HEMSCH0_N
	MX_HEMSCH0_USR
	MX_HEMSCH0_URDY0
	M_TXTRIG_FLAG
	M_TXTRIG_NUM
	M_TXTRIG_LEN
	M_TXTRIG_RATE
	M_MUAGG_HISTO
	M_HEMMUAGG_HISTO
	M_HEOMUAGG_HISTO
	M_TXAMPDUSU_CNT
	M_TXTRIG_MINTIME
	M_TXTRIG_FRAME
	M_TXTRIG_CMNINFO
	M_ULRXCTL_BLK
	M_RTS_MINLEN_L
	M_RTS_MINLEN_H
	M_AGG0_CNT
	M_TRIGREFILL_CNT
	M_TXTRIG_CNT
	M_RXHETBBA_CNT
	M_TXBAMTID_CNT
	M_TXBAMSTA_CNT
	M_TXMBA_CNT
	M_RXMYDTINRSP
	M_RXEXIT_CNT
	M_PHYRXSFULL_CNT
	M_BFECAP_HE
	M_BFECAP_VHT
	M_BFECAP_HT
	M_BSS_BLK
	MX_MUBFI_BLK
	M_TXTRIG_SRXCTL
	M_TXTRIG_SRXCTLUSR
	M_ULTX_STS
	M_BCN_TXPCTL6
	MX_OQEXPECTN_BLK
	MX_OQMAXN_BLK
	MX_OMSCH_TMOUT
	MX_SNDREQ_BLK
	M_BFI_GENCFG
	MX_TRIG_TXCFG
	MX_TRIG_TXLMT
	M_PHYREG_TDSFO_VAL
	M_PHYREG_HWOBSS_VAL
	M_BSS_BSRT_BLK
	MX_WRR_QUOTA
	MX_WRR_HISTO
	M_STXVM_BLK
	MX_TXVBMP_BLK
	MX_MRQ_UPDPEND
	MX_TXVM_BLK
	MX_CQIBMP_BLK
	MX_CQIM_BLK
	M_TXBRPTRIG_CNT
	MX_MACREQ_BLK
	M_TXVMSTATS_BLK
	M_CQIMSTATS_BLK
	M_TXVFULL_CNT
	MX_SNDAGE_THRSH
	M_HETB_CSTHRSH_LO
	M_HETB_CSTHRSH_HI
	MX_CURCHANNEL
	MX_OQMINN_BLK
	M_D11SR_BLK
	M_D11SR_NSRG_PDMIN
	M_D11SR_NSRG_PDMAX
	M_D11SR_SRG_PDMIN
	M_D11SR_SRG_PDMAX
	M_D11SR_TXPWRREF
	M_D11SR_NSRG_TXPWRREF0
	M_D11SR_SRG_TXPWRREF0
	M_TWTCMD
	M_TWTINT_DATA
	M_PRETWT_US
	M_TWT_PRESTRT
	M_TWT_PRESTOP
	MX_TWT_PRESTRT
	MX_ULOMAXN_BLK
	M_TXTRIGWT0_VAL
	M_TXTRIGWT1_VAL
	MX_ULC_NUM
	MX_M2VMSG_CNT
	MX_V2MMSG_CNT
	MX_SFB2V_CNT
	MX_V2GRP_CNT
	MX_MVP2V_CNT
	MX_V2MVP_CNT
	MX_M2VCQI_CNT
	MX_V2MCQI_CNT
	MX_FFQADD_CNT
	MX_MFQADD_CNT
	MX_MFOQADD_CNT
	MX_OFQADD_CNT
	MX_RUCFG_CNT
	MX_M2VRU_CNT
	MX_V2MRU_CNT
	MX_OFQAGG0_CNT
	MX_ULO_QNULLTHRSH
FEATURE_END

# Following feature is for SHMs present in EAP ucode
FEATURE_BEGIN[eap]
	M_DTIM_TXENQD_BMBP
	M_DTIMCNT_MBSS_BMBP
	M_ODAP_ACK_TMOUT
	M_ODAP_ACK_TMOUT_TEST
	M_MBS_DAGGOFF_BMP
	M_CTRL_CHANNEL
	M_ENT_HOST_FLAGS1
	M_EAP_BLK_0
	M_EAP_BLK_1
	M_UCODE_CAP_L
	M_UCODE_CAP_H
	M_UCODE_FEATURE_EN_L
	M_UCODE_FEATURE_EN_H
	M_PRS_RETRY_THR
	M_MBSS_CCK_BITMAP
	M_GEN_DBG0
	M_EAP_BLK_2
	M_SAS_DEBUG_BLK
	M_EAPSC1_SUCC_CNT
	M_EAPSC1_FAIL_CNT
	M_EAPSP1_SUCC_CNT
	M_EAPSP1_FAIL_CNT
	M_EAPFC_SUCC_CNT
	M_EAPFC_FAIL_CNT
	M_EAPFC1_SUCC_CNT
	M_EAPFC1_FAIL_CNT
	M_SAS_RESP_AI_BLK
	M_DTIM_MBSS_BLK
	M_TIM_OFF_MBSS_BLK
	M_SAS_RESP_AI_IDX
	M_SAS_RESP_AI_BLK_PTR
	M_SAS_DBG_4
	M_SAS_DBG_5
	M_SASAIFIFO_OFLO_CNT
	M_TXQ_PRUNE_TABLE
	M_FFT_SMPL_FFT_GAIN_RX0
	M_FFT_SMPL_FFT_GAIN_RX1
	M_FFT_SMPL_FFT_GAIN_RX2
	M_FFT_SMPL_CTRL
	M_FFT_SMPL_TS
	M_FFT_SMPL_FRAME_COUNT
	M_FFT_SMPL_RX_CHAIN
	M_SASAIFIFO_RPTR
	M_SASAIFIFO_WPTR
	M_FFT_SMPL_TIMER_TIMESTAMP
	M_FFT_SMPL_WLAN_GAIN_RX0
	M_FFT_SMPL_WLAN_GAIN_RX1
	M_FFT_SMPL_WLAN_GAIN_RX2
	M_FFT_SMPL_STATUS
	M_FFT_SMPL_SEQUENCE_NUM
	M_FFT_CRS_GLITCH_CNT
	M_FAST_NOISE_TS
	M_FAST_NOISE_DIFF
	M_SAS_FRM_RX_AI
	M_SAS_IMPBF_AI
	M_FAST_NOISE_FORCE
	M_FFT_SMPL_CHANNEL
	M_FFT_SMPL_FFT_GAIN_RX3
	M_FAST_NOISE_MEASURE
	M_FAST_NOISE_DUR
	M_SAS_DEFAULT_AI_RXD
	M_SAS_DEFAULT_AI_TXD
	M_SAS_GPIO_CLK
	M_SAS_GPIO_DATA
	M_FFT_SMPL_ENABLE
	M_FFT_SMPL_INTERVAL
	M_EAP_BLK_RESERVED_1
	M_EAP_BLK_RESERVED_2
	M_FFT_PHYTABLE_LOCK
	M_FIPS_LOOPBACK_IV0
	M_FIPS_LOOPBACK_IV1
	M_FIPS_LOOPBACK_IV2
	M_FIPS_LOOPBACK_IV3
	M_FIPS_LOOPBACK_IV4
	M_FIPS_LOOPBACK_IV5
	M_FIPS_LOOPBACK_IV6
	M_FIPS_LOOPBACK_IV7
	M_FIPS_LOOPBACK_PLEN
	M_NM_ATTEMPTS
	M_NM_IFS_START
	M_NM_IFS_END
	M_NM_EDCRS
	M_NM_PKTPROC
	M_NM_POST_CLEAN
	M_NM_PKTPROC2		# 11ax only
	M_NM_IFS_MID		# 11ax only
	M_DIAG_FLAGS
FEATURE_END
